interface Env { DB: D1Database; ASSETS: Fetcher; }
const json=(data:unknown,init:ResponseInit={})=>new Response(JSON.stringify(data),{...init,headers:{"content-type":"application/json; charset=utf-8",...init.headers}});
const bad=(code:string,message:string,status=400)=>json({error:{code,message}},{status});
const body=async(request:Request)=>{try{return await request.json() as Record<string,unknown>}catch{return null}};
const textValue=(v:unknown)=>typeof v==="string"&&v.trim()?v.trim():null;
export default { async fetch(request:Request,env:Env):Promise<Response>{
 const url=new URL(request.url); if(!url.pathname.startsWith("/api/")) return env.ASSETS.fetch(request);
 if(request.method==="GET"&&url.pathname==="/api/health"){const row=await env.DB.prepare("SELECT 1 AS ok").first<{ok:number}>();return json({ok:row?.ok===1});}
 if(request.method==="GET"&&url.pathname==="/api/groups"){const r=await env.DB.prepare("SELECT id,name,created_at AS createdAt,updated_at AS updatedAt FROM groups ORDER BY created_at,id").all();return json({groups:r.results});}
 if(request.method==="POST"&&url.pathname==="/api/groups"){const b=await body(request),id=textValue(b?.id),name=textValue(b?.name),createdAt=textValue(b?.createdAt),updatedAt=textValue(b?.updatedAt);if(!id||!name||!createdAt||!updatedAt)return bad("invalid_group","id, name, createdAt and updatedAt are required");try{await env.DB.prepare("INSERT INTO groups(id,name,created_at,updated_at) VALUES(?,?,?,?)").bind(id,name,createdAt,updatedAt).run();return json({group:{id,name,createdAt,updatedAt}},{status:201});}catch{return bad("group_write_failed","Group could not be created",409);}}
 const m=url.pathname.match(/^\/api\/groups\/([^/]+)\/players$/);if(request.method==="GET"&&m){const groupId=decodeURIComponent(m[1]);const r=await env.DB.prepare("SELECT p.id,p.display_name AS displayName,p.created_at AS createdAt,p.updated_at AS updatedAt FROM players p JOIN group_players gp ON gp.player_id=p.id WHERE gp.group_id=? AND gp.active=1 ORDER BY p.created_at,p.id").bind(groupId).all();return json({players:r.results});}
 if(request.method==="POST"&&m){const groupId=decodeURIComponent(m[1]),b=await body(request),id=textValue(b?.id),displayName=textValue(b?.displayName),createdAt=textValue(b?.createdAt),updatedAt=textValue(b?.updatedAt);if(!id||!displayName||!createdAt||!updatedAt)return bad("invalid_player","id, displayName, createdAt and updatedAt are required");try{await env.DB.batch([env.DB.prepare("INSERT INTO players(id,display_name,created_at,updated_at) VALUES(?,?,?,?)").bind(id,displayName,createdAt,updatedAt),env.DB.prepare("INSERT INTO group_players(group_id,player_id,active) VALUES(?,?,1)").bind(groupId,id)]);return json({player:{id,displayName,createdAt,updatedAt}},{status:201});}catch{return bad("player_write_failed","Player could not be created",409);}}
 return bad("not_found","Not found",404);
 }} satisfies ExportedHandler<Env>;
